sleeperbox/client

component/pages/form-user/login.js
component/pages/form-user/register.js

Im doing Fixing Responsive of Alternate Button in Login and Register

Fixing Responsive of Alternate Button in Login and Register

---

component/pages/profile/HeaderProfile.js

Change Avatar Profile Into Valid Design

Change Avatar Profile Into Valid Design

---

component/functions/Formlogin.css
component/functions/Formlogin.js
component/functions/Hello.js
component/pages/category/notification/index.js
component/pages/form-user/login.js
component/pages/form-user/register.js

Centering Notification Content

Centering Notification Content

---

component/pages/category/photo/Content.js

skeleton for user photo page

---

component/pages/profile/HeaderProfile.js

making user post - reputation, tinggal ubah img ajah dan if menyesuaikan dengan img

making user post - reputation,

---

component/pages/profile/MenuProfile.js

fixed notification status in user

notif fixed

---

component/pages/posts/TagsPost.js
component/pages/profile/MoreCategory.js
component/pages/profile/MyPost.js

UI Fix On Profile and Tags Category

UI Fix On Profile and Tags Category

---

component/pages/category/setting/account-setting.js
component/pages/category/setting/profile-setting.js

Fixing Setting Menu

---

component/pages/home/ContentCategory.js
component/pages/home/content.js
component/pages/home/index.js
component/pages/profile/MenuProfile.js
index.js

Fixing Category Post

---

component/pages/form-user/register.js

Remove ? Icon on Create New Icon Menu

Remove ? Icon on Create New Icon Menu

---

component/pages/category/setting/profile-setting.js

fix bug validate number in fild myphone

fix validate number

---

component/pages/category/setting/account-setting.js
component/pages/category/setting/profile-setting.js

rearange in setting

---

component/pages/profile/MyPost.js

Make space in Posting

---

component/pages/people-profile/Action.js
component/pages/people-profile/Posts.js

Other People Fix

---

component/pages/category/notification/index.js
component/pages/category/setting/index.js
component/pages/category/statistic/index.js
component/pages/home/index.js
component/pages/message/index.js
component/pages/profile/index.js

add loading all page in user

---

component/pages/category/setting/profile-setting.js

fix Tags in setting page

---

component/pages/category/notification/index.js
component/pages/category/people/index.js
component/pages/category/setting/index.js
component/pages/category/statistic/index.js
component/pages/home/index.js
component/pages/message/index.js
component/pages/profile/index.js

fix loading in home, profil, notif, statistic, people, setting

Fix loading

---

component/pages/home/Navbar.js
component/pages/home/PostingBussinessWork.js
component/pages/home/PostingComputerGadget.js
component/pages/home/PostingFactRumour.js
component/pages/home/PostingFamilyLove.js
component/pages/home/PostingFashionLifestyle.js
component/pages/home/PostingOther.js
component/pages/home/PostingQuotes.js
component/pages/home/PostingRiddles.js
component/pages/home/index.js

Fixing Home

---

component/pages/category/setting/account-setting.js
component/pages/category/setting/index.js
component/pages/category/setting/profile-setting.js
component/pages/profile/HeaderProfile.js
index.css
index.js

change font all, and than i change buton and form setting

change font and form setting

---

component/pages/home/PostingBussinessWork.js
component/pages/home/PostingComputerGadget.js
component/pages/home/PostingFactRumour.js
component/pages/home/PostingFamilyLove.js
component/pages/home/PostingFashionLifestyle.js
component/pages/home/PostingOther.js
component/pages/home/PostingQuotes.js
component/pages/home/PostingRiddles.js
component/pages/people-profile/Posts.js
component/pages/profile/MyPost.js

Fix Date Time Posting

---

component/pages/category/people/allPeople.js

add button message and to chage color button

add button message

---

component/pages/message/index.js

bugfix button + messege

---

component/pages/category/people/allPeople.js
component/pages/profile/HeaderProfile.js

fix img in show profil friend and my profil

---

component/pages/category/notification/HeaderNotification.js
component/pages/category/notification/goBack.js
component/pages/home/Navbar.js
component/pages/message/HeaderMessage.js

fix bugs in back

---

component/pages/profile/MyPost.js

Add Total Comment

---

component/pages/discuss/Posts.js
component/pages/profile/MyPost.js

Add time and date on comment

---

component/pages/category/store/Store.js
component/pages/category/store/index.js

Comming Soon Store

---

component/pages/category/store/Store.js

Coming Soon Notif Bugfix

---

component/pages/profile/Hex.css
component/pages/profile/MyPost.js

Fix post picture on profile

---

component/pages/MessagePrivate/index.js
component/pages/MessagePrivate/style.css

fix input message

---

component/pages/MessagePrivate/index.js
component/pages/discuss/Posts.js
component/pages/message/index.js
component/pages/newmessage/Contack.js
component/pages/newmessage/HeaderNewMessage.js

fix input comment

---

component/pages/profile/MenuProfile.js
component/pages/profile/Post.js
component/pages/profile/app.css
index.js

fix posting input

---

component/pages/profile/MoreCategory.js

Show Ranking on My Reputation

---

component/pages/category/people/allPeople.js

 Show Ranking On People Menu

---

component/pages/category/setting/profile-setting.js

validation on phone number

---

component/pages/category/notification/comment.js
component/pages/category/notification/infuenced.js
component/pages/profile/MenuProfile.js

Bugfix MenuProfile

---

component/pages/form-user/register.js
component/pages/message/index.js
component/pages/newmessage/Contack.js

Fix Message

---

component/pages/MessagePrivate/index.js
component/pages/discuss/Posts.js

Chatbox in Chat

---

component/pages/home/PostingBussinessWork.js
component/pages/home/PostingComputerGadget.js
component/pages/home/PostingFactRumour.js
component/pages/home/PostingFamilyLove.js
component/pages/home/PostingFashionLifestyle.js
component/pages/home/PostingOther.js
component/pages/home/PostingQuotes.js
component/pages/home/PostingRiddles.js
component/pages/profile/MyPost.js

Bugfix myPost

---

component/pages/profile/MyPost.js
component/pages/profile/MyPostLightWeight.js

bugfix profile
